### ISSUE TITLE
Possible logic error in generation process

### ISSUE THREAD

**Issue by etjk** [CS2103-AY1819S1-W17-2/main#213]
Let's say now we have the following module in db:
CS1010, CS1231, CS2030 (requires cs1010), CS2040(requires cs1010)

If I were to add CS2030 and CS2040 to Taken first. 
Then I add CS1010 to staged. 

I have tried the above flow and it generates normally for CS1231 and CS1010. But I'm not sure if are any side effect.

@RTJL please provide your inputs on this matter.

**Comment by RTJL** [comment]
As discussed in our telegram group chat, we may want to implement checks before allowing users to add a module to their "Taken" list. There won't be any errors thrown in the given scenario.
