### ISSUE TITLE
Feedback on week 6 project progress

### ISSUE THREAD

**Issue by asiddharth** [CS2103-AY1819S1-W17-2/main#43]
Subject: feedback on week 6 project progress 

See [mid-v1.1 progress guide](https://nus-cs2103-ay1819s1.github.io/cs2103-website/admin/project-w06-mid-v11.html) for more details of the activities mentioned below. 

### Progress noted (well done! :+1:):
* Team org and repo set up with the correct names.
* PR created from team repo to [AB-4](https://github.com/nus-cs2103-AY1819S1/addressbook-level4).

### Suggestions (to do soon):
None

### Progress noted (well done! :+1:):
* Team repo forked to your GitHub account.
* PRs created to update documents.

### Suggestions (to do soon):
* Create PRs to do a local change to the Java code.

### Progress noted (well done! :+1:):
* Team repo forked to your GitHub account.

### Suggestions (to do soon):
* Create PRs for your share of updating documents.
* Create PRs to do a local change to the Java code.

### Progress noted (well done! :+1:):
* Team repo forked to your GitHub account.

### Suggestions (to do soon):
* Create PRs for your share of updating documents.
* Create PRs to do a local change to the Java code.

### Progress noted (well done! :+1:):
* PRs created to update documents.

### Suggestions (to do soon):
* Fork team repo to your GitHub account.
* Create PRs to do a local change to the Java code.

### Progress noted (well done! :+1:):
* PRs created to update documents.

### Suggestions (to do soon):
* Fork team repo to your GitHub account.
* Create PRs to do a local change to the Java code.

Tutor: @amrut-prabhu

Note: the above observation was done by the CS2103-feedback-bot and covers changes up to 18/9/2018 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.

**Comment by CrimsonJacket** [comment]
@asiddharth 
There might be certain discrepancies with some of the aforementioned observations regarding the Forking of Team Repo and PRs.

> Fork Team Repo to your GitHub Account

https://github.com/CrimsonJacket/modsUni
https://github.com/RTJL/main
Both @RTJL and myself did forked our Team Repo as seen above.

> Create PRs to do a local change to the Java code.

https://github.com/CS2103-AY1819S1-W17-2/main/pulls?q=is%3Apr+is%3Aclosed

The above link should proof that all members have created PRs to do a local change

**Comment by RTJL** [comment]
hi @asiddharth, is there any update to the above comment?
